[project]
name = "mpc2creo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "openeo>=0.45.0",
    "orjson>=3.10.18",
    "pydantic>=2.11.7",
    "pystac-client>=0.8.6",
    "pyyaml>=6.0.2",
    "stac-asset>=0.4.7",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
